# Generated by Django 5.0.7 on 2024-10-31 09:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('last_active', models.DateField(null=True)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('limit', models.IntegerField(default=100)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default_project')),
                ('limit', models.IntegerField(default=100)),
                ('status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('version', models.CharField(
                    max_length=255, primary_key=True, serialize=False)),
                ('setup_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccountJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField()),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccountProjectJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.project')),
            ],
        ),
    ]
