# Generated by Django 5.1.2 on 2024-11-01 20:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=255, null=True)),
                ('password_salt', models.CharField(max_length=255, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='invited')),
                ('access_level', models.CharField(default='regular')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(default='active')),
                ('plan', models.CharField(default='unlimited')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default_project')),
                ('limit', models.IntegerField(default=0)),
                ('status', models.CharField(default='active')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('version', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('setup_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccountJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_role', models.CharField(default='user')),
                ('current', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccountProjectJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_role', models.CharField(default='tester')),
                ('organization_role', models.CharField(default='user')),
                ('current', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docyou.organization')),
            ],
        ),
    ]
