# Generated by Django 5.1.2 on 2024-11-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docyou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interface_theme',
            field=models.CharField(default='light'),
        ),
    ]
